export const AUDITOR_REQUEST_GET = "AUDITOR_REQUEST_GET";
export const AUDITOR_SUCCESS_GET = "AUDITOR_SUCCESS_GET";
export const AUDITOR_GET_FAIL = "AUDITOR_GET_FAIL";

export const EXECUTIVE_REQUEST_GET = "EXECUTIVE_REQUEST_GET";
export const EXECUTIVE_SUCCESS_GET = "EXECUTIVE_SUCCESS_GET";
export const EXECUTIVE_GET_FAIL = "EXECUTIVE_GET_FAIL";

export const AUDIT_REQUEST_CREATE = "AUDIT_REQUEST_CREATE";
export const AUDIT_SUCCESS_CREATE = "AUDIT_SUCCESS_CREATE";
export const AUDIT_FAIL_CREATE = "AUDIT_FAIL_CREATE";

export const CHECKLIST_REQUEST_GET_CREATE_AUDIT = "CHECKLIST_REQUEST_GET_CREATE_AUDIT";
export const CHECKLIST_SUCCESS_GET_CREATE_AUDIT = "CHECKLIST_SUCCESS_GET_CREATE_AUDIT";
export const CHECKLIST_GET_FAIL_CREATE_AUDIT = "CHECKLIST_GET_FAIL_CREATE_AUDIT";

export const AUDITOR_REQUEST_GET_FILTER = "AUDITOR_REQUEST_GET_FILTER";
export const AUDITOR_SUCCESS_GET_FILTER = "AUDITOR_SUCCESS_GET_FILTER";
export const AUDITOR_GET_FAIL_FILTER = "AUDITOR_GET_FAIL_FILTER";

export const AUDITOR_REQUEST_GET_ALL_FILTER = "AUDITOR_REQUEST_GET_ALL_FILTER";
export const AUDITOR_SUCCESS_GET_ALL_FILTER = "AUDITOR_SUCCESS_GET_ALL_FILTER";
export const AUDITOR_GET_FAIL_ALL_FILTER = "AUDITOR_GET_FAIL_ALL_FILTER";

export const AUDIT_REQUEST_ONGOING_DETAIL = "AUDIT_REQUEST_ONGOING_DETAIL";
export const AUDIT_SUCCESS_ONGOING_DETAIL = "AUDIT_SUCCESS_ONGOING_DETAIL";
export const AUDIT_FAIL_ONGOING_DETAIL = "AUDIT_FAIL_ONGOING_DETAIL";

export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";

export const CATEGORY_REQUEST_GET = "CATEGORY_REQUEST_GET";
export const CATEGORY_SUCCESS_GET = "CATEGORY_SUCCESS_GET";
export const CATEGORY_GET_FAIL = "CATEGORY_GET_FAIL";

export const CATEGORY_REQUEST_EDIT = "CATEGORY_REQUEST_EDIT";
export const CATEGORY_SUCCESS_EDIT = "CATEGORY_SUCCESS_EDIT";
export const CATEGORY_EDIT_FAIL = "CATEGORY_EDIT_FAIL";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";

export const STATE_REQUEST_GET = "STATE_REQUEST_GET";
export const STATE_SUCCESS_GET = "STATE_SUCCESS_GET";
export const STATE_GET_FAIL = "STATE_GET_FAIL";

export const USER_REQUEST_GET = "USER_REQUEST_GET";
export const USER_SUCCESS_GET = "USER_SUCCESS_GET";
export const USER_GET_FAIL = "USER_GET_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const NOTFICATION_CREATE_REQUEST = "NOTFICATION_CREATE_REQUEST";
export const NOTFICATION_CREATE_SUCCESS = "NOTFICATION_CREATE_SUCCESS";
export const NOTFICATION_CREATE_FAIL = "NOTFICATION_CREATE_FAIL";

export const NOTFICATION_REQUEST_GET = "NOTFICATION_REQUEST_GET";
export const NOTFICATION_SUCCESS_GET = "NOTFICATION_SUCCESS_GET";
export const NOTFICATION_GET_FAIL = "NOTFICATION_GET_FAIL";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";

export const USER_REQUEST_EDIT = "USER_REQUEST_EDIT";
export const USER_SUCCESS_EDIT = "USER_SUCCESS_EDIT";
export const USER_EDIT_FAIL = "USER_EDIT_FAIL";

export const CHECKLIST_CREATE_REQUEST = "CHECKLIST_CREATE_REQUEST";
export const CHECKLIST_CREATE_SUCCESS = "CHECKLIST_CREATE_SUCCESS";
export const CHECKLIST_CREATE_FAIL = "CHECKLIST_CREATE_FAIL";

export const CHECKLIST_REQUEST_GET = "CHECKLIST_REQUEST_GET";
export const CHECKLIST_SUCCESS_GET = "CHECKLIST_SUCCESS_GET";
export const CHECKLIST_GET_FAIL = "CHECKLIST_GET_FAIL";

export const CHECKLIST_REQUEST_UPDATE_BYID = "CHECKLIST_REQUEST_UPDATE_BYID";
export const CHECKLIST_SUCCESS_UPDATE_BYID = "CHECKLIST_SUCCESS_UPDATE_BYID";
export const CHECKLIST_FAIL_UPDATE_BYID = "CHECKLIST_FAIL_UPDATE_BYID";

export const CHECKLIST_REQUEST_GET_CREATE = "CHECKLIST_REQUEST_GET_CREATE";
export const CHECKLIST_SUCCESS_GET_CREATE = "CHECKLIST_SUCCESS_GET_CREATE";
export const CHECKLIST_GET_FAIL_CREATE = "CHECKLIST_GET_FAIL_CREATE";

export const CHECKLIST_REQUEST_GET_BYID = "CHECKLIST_REQUEST_GET_BYID";
export const CHECKLIST_SUCCESS_GET_BYID = "CHECKLIST_SUCCESS_GET_BYID";
export const CHECKLIST_FAIL_GET_BYID = "CHECKLIST_FAIL_GET_BYID";

export const CHECKLIST_REQUEST_GET_ALL = "CHECKLIST_REQUEST_GET_ALL";
export const CHECKLIST_SUCCESS_GET_ALL = "CHECKLIST_SUCCESS_GET_ALL";
export const CHECKLIST_GET_FAIL_ALL = "CHECKLIST_GET_FAIL_ALL";

export const CHECKLIST_REQUEST_GET_APPROVE = "CHECKLIST_REQUEST_GET_APPROVE";
export const CHECKLIST_SUCCESS_GET_APPROVE = "CHECKLIST_SUCCESS_GET_APPROVE";
export const CHECKLIST_REQUEST_GET_APPROVE_FAIL = "CHECKLIST_REQUEST_GET_APPROVE_FAIL";

export const CHECKLIST_REQUEST_ALL_FILTER = "CHECKLIST_REQUEST_ALL_FILTER";
export const CHECKLIST_SUCCESS_ALL_FILTER = "CHECKLIST_SUCCESS_ALL_FILTER";
export const CHECKLIST_ALL_FAIL_FILTER = "CHECKLIST_ALL_FAIL_FILTER";

export const CHECKLIST_REQUEST_CREATE_FILTER = "CHECKLIST_REQUEST_CREATE_FILTER";
export const CHECKLIST_SUCCESS_CREATE_FILTER = "CHECKLIST_SUCCESS_CREATE_FILTER";
export const CHECKLIST_ALL_CREATE_FILTER = "CHECKLIST_ALL_CREATE_FILTER";

export const CHECKLIST_REQUEST_All_COMPLIANCE = "CHECKLIST_REQUEST_All_COMPLIANCE";
export const CHECKLIST_SUCCESS_All_COMPLIANCE = "CHECKLIST_SUCCESS_All_COMPLIANCE";
export const CHECKLIST_FAIL_All_COMPLIANCE = "CHECKLIST_FAIL_All_COMPLIANCE";

export const CHECKLIST_REQUEST_REJECT_FILTER = "CHECKLIST_REQUEST_REJECT_FILTER";
export const CHECKLIST_SUCCESS_REJECT_FILTER = "CHECKLIST_SUCCESS_REJECT_FILTER";
export const CHECKLIST_ALL_REJECT_FILTER = "CHECKLIST_ALL_REJECT_FILTER";

export const CHECKLIST_REQUEST_REJECT = "CHECKLIST_REQUEST_REJECT";
export const CHECKLIST_SUCCESS_REJECT = "CHECKLIST_SUCCESS_REJECT";
export const CHECKLIST_REQUEST_REJECT_FAIL = "CHECKLIST_REQUEST_REJECT_FAIL";

export const CHECKLIST_REQUEST_GET_REJECT = "CHECKLIST_REQUEST_GET_REJECT";
export const CHECKLIST_SUCCESS_GET_REJECT = "CHECKLIST_SUCCESS_GET_REJECT";
export const CHECKLIST_GET_FAIL_REJECT = "CHECKLIST_GET_FAIL_REJECT";

export const AUDIT_REQUEST_All_DETAIL = "AUDIT_REQUEST_All_DETAIL";
export const AUDIT_SUCCESS_All_DETAIL = "AUDIT_SUCCESS_All_DETAIL";
export const AUDIT_FAIL_All_DETAIL = "AUDIT_FAIL_All_DETAIL";

export const BRANCH_REQUEST_GET = "BRANCH_REQUEST_GET";
export const BRANCH_SUCCESS_GET = "BRANCH_SUCCESS_GET";
export const BRANCH_GET_FAIL = "BRANCH_GET_FAIL";

export const COMPANY_REQUEST_GET = "COMPANY_REQUEST_GET";
export const COMPANY_SUCCESS_GET = "COMPANY_SUCCESS_GET";
export const COMPANY_GET_FAIL = "COMPANY_GET_FAIL";

export const COMPLIANCE_REQUEST_GET = "COMPLIANCE_REQUEST_GET";
export const COMPLIANCE_SUCCESS_GET = "COMPLIANCE_SUCCESS_GET";
export const COMPLIANCE_GET_FAIL = "COMPLIANCE_GET_FAIL";

export const CHECKLIST_REQUEST_APPROVE_FILTER = "CHECKLIST_REQUEST_APPROVE_FILTER";
export const CHECKLIST_SUCCESS_APPROVE_FILTER = "CHECKLIST_SUCCESS_APPROVE_FILTER";
export const CHECKLIST_ALL_APPROVE_FILTER = "CHECKLIST_ALL_APPROVE_FILTER";

export const CHECKLIST_REQUEST_GET_APPROVE_PAGE = "CHECKLIST_REQUEST_GET_APPROVE_PAGE";
export const CHECKLIST_SUCCESS_GET_APPROVE_PAGE = "CHECKLIST_SUCCESS_GET_APPROVE_PAGE";
export const CHECKLIST_GET_FAIL_APPROVE_PAGE = "CHECKLIST_GET_FAIL_APPROVE_PAGE";

export const COMPLIANCE_REQUEST_APPROVE_FILTER = "COMPLIANCE_REQUEST_APPROVE_FILTER";
export const COMPLIANCE_SUCCESS_APPROVE_FILTER = "COMPLIANCE_SUCCESS_APPROVE_FILTER";
export const COMPLIANCE_APPROVE_FAIL_FILTER = "COMPLIANCE_APPROVE_FAIL_FILTER";

export const COMPLIANCE_SUCCESS_GET_ALL_FILTER = "COMPLIANCE_SUCCESS_GET_ALL_FILTER";
export const COMPLIANCE_REQUEST_GET_ALL_FILTER = "COMPLIANCE_REQUEST_GET_ALL_FILTER";
export const COMPLIANCE_GET_FAIL_ALL_FILTER = "COMPLIANCE_GET_FAIL_ALL_FILTER";

export const COMPLIANCE_REQUEST_REJECT_FILTER = "COMPLIANCE_REQUEST_REJECT_FILTER";
export const COMPLIANCE_SUCCESS_REJECT_FILTER = "COMPLIANCE_SUCCESS_REJECT_FILTER";
export const COMPLIANCE_REJECT_FAIL_FILTER = "COMPLIANCE_REJECT_FAIL_FILTER";

export const COMPLIANCE_REQUEST_GET_ALL = "COMPLIANCE_REQUEST_GET_ALL";
export const COMPLIANCE_SUCCESS_GET_ALL = "COMPLIANCE_SUCCESS_GET_ALL";
export const COMPLIANCE_GET_FAIL_ALL = "COMPLIANCE_GET_FAIL_ALL";

export const COMPLIANCE_REQUEST_GET_CREATE = "COMPLIANCE_REQUEST_GET_CREATE";
export const COMPLIANCE_SUCCESS_GET_CREATE = "COMPLIANCE_SUCCESS_GET_CREATE";
export const COMPLIANCE_GET_FAIL_CREATE = "COMPLIANCE_GET_FAIL_CREATE";

export const COMPLIANCE_REQUEST_GET_BYID = "COMPLIANCE_REQUEST_GET_BYID";
export const COMPLIANCE_SUCCESS_GET_BYID = "COMPLIANCE_SUCCESS_GET_BYID";
export const COMPLIANCE_FAIL_GET_BYID = "COMPLIANCE_FAIL_GET_BYID";

export const BRANCH_CREATE_REQUEST = "BRANCH_CREATE_REQUEST";
export const BRANCH_CREATE_SUCCESS = "BRANCH_CREATE_SUCCESS";
export const BRANCH_CREATE_FAIL = "BRANCH_CREATE_FAIL";

export const COMPANY_CREATE_REQUEST = "COMPANY_CREATE_REQUEST";
export const COMPANY_CREATE_SUCCESS = "COMPANY_CREATE_SUCCESS";
export const COMPANY_CREATE_FAIL = "COMPANY_CREATE_FAIL";

export const COMPLIANCE_CREATE_REQUEST = "COMPLIANCE_CREATE_REQUEST";
export const COMPLIANCE_CREATE_SUCCESS = "COMPLIANCE_CREATE_SUCCESS";
export const COMPLIANCE_CREATE_FAIL = "COMPLIANCE_CREATE_FAIL";

export const COMPLIANCE_REQUEST_UPDATE_BYID = "COMPLIANCE_REQUEST_UPDATE_BYID";
export const COMPLIANCE_SUCCESS_UPDATE_BYID = "COMPLIANCE_SUCCESS_UPDATE_BYID";
export const COMPLIANCE_FAIL_UPDATE_BYID = "COMPLIANCE_FAIL_UPDATE_BYID";

export const COMPLIANCE_REQUEST_GET_APPROVE = "COMPLIANCE_REQUEST_GET_APPROVE";
export const COMPLIANCE_SUCCESS_GET_APPROVE = "COMPLIANCE_SUCCESS_GET_APPROVE";
export const COMPLIANCE_REQUEST_GET_APPROVE_FAIL = "COMPLIANCE_REQUEST_GET_APPROVE_FAIL";

export const COMPLIANCE_REQUEST_GET_FILTER = "COMPLIANCE_REQUEST_GET_FILTER";
export const COMPLIANCE_SUCCESS_GET_FILTER = "COMPLIANCE_SUCCESS_GET_FILTER";
export const COMPLIANCE_GET_FAIL_FILTER = "COMPLIANCE_GET_FAIL_FILTER";

export const COMPLIANCE_REQUEST_GET_REJECT = "COMPLIANCE_REQUEST_GET_REJECT";
export const COMPLIANCE_SUCCESS_GET_REJECT = "COMPLIANCE_SUCCESS_GET_REJECT";
export const COMPLIANCE_REQUEST_GET_REJECT_FAIL = "COMPLIANCE_REQUEST_GET_REJECT_FAIL";

export const COMPLIANCE_REQUEST_REJECT = "COMPLIANCE_REQUEST_REJECT";
export const COMPLIANCE_SUCCESS_REJECT = "COMPLIANCE_SUCCESS_REJECT";
export const COMPLIANCE_REQUEST_REJECT_FAIL = "COMPLIANCE_REQUEST_REJECT_FAIL";

export const NAMERATE_CREATE_REQUEST = "NAMERATE_CREATE_REQUEST";
export const NAMERATE_CREATE_SUCCESS = "NAMERATE_CREATE_SUCCESS";
export const NAMERATE_CREATE_FAIL = "NAMERATE_CREATE_FAIL";

export const DOC_CREATE_REQUEST = "DOC_CREATE_REQUEST";
export const DOC_CREATE_SUCCESS = "DOC_CREATE_SUCCESS";
export const DOC_CREATE_FAIL = "DOC_CREATE_FAIL";

export const APPDETAILS_CREATE_REQUEST = "APPDETAILS_CREATE_REQUEST";
export const APPDETAILS_CREATE_SUCCESS = "APPDETAILS_CREATE_SUCCESS";
export const APPDETAILS_CREATE_FAIL = "APPDETAILS_CREATE_FAIL";

export const EXPENSE_CREATE_REQUEST = "EXPENSE_CREATE_REQUEST";
export const EXPENSE_CREATE_SUCCESS = "EXPENSE_CREATE_SUCCESS";
export const EXPENSE_CREATE_FAIL = "EXPENSE_CREATE_FAIL";

export const LICENSE_CREATE_REQUEST = "LICENSE_CREATE_REQUEST";
export const LICENSE_CREATE_SUCCESS = "LICENSE_CREATE_SUCCESS";
export const LICENSE_CREATE_FAIL = "LICENSE_CREATE_FAIL";

export const INVOICE_CREATE_REQUEST = "INVOICE_CREATE_REQUEST";
export const INVOICE_CREATE_SUCCESS = "INVOICE_CREATE_SUCCESS";
export const INVOICE_CREATE_FAIL = "INVOICE_CREATE_FAIL";

export const COMPANYINFO_CREATE_REQUEST = "COMPANYINFO_CREATE_REQUEST";
export const COMPANYINFO_CREATE_SUCCESS = "COMPANYINFO_CREATE_SUCCESS";
export const COMPANYINFO_CREATE_FAIL = "COMPANYINFO_CREATE_FAIL";

export const REGSGET_REQUEST = "REGSGET_REQUEST";
export const REGSGET_SUCCESS = "REGSGET_SUCCESS";
export const REGSGET_FAIL = "REGSGET_FAIL";

export const LISEREGS_REQUEST_GET_APPROVE = "LISEREGS_REQUEST_GET_APPROVE";
export const LISEREGS_SUCCESS_GET_APPROVE = "LISEREGS_SUCCESS_GET_APPROVE";
export const LISEREGS_REQUEST_GET_APPROVE_FAIL = "LISEREGS_REQUEST_GET_APPROVE_FAIL";

export const LISEREGS_REQUEST_GET_FILTER = "LISEREGS_REQUEST_GET_FILTER";
export const LISEREGS_SUCCESS_GET_FILTER = "LISEREGS_SUCCESS_GET_FILTER";
export const LISEREGS_REQUEST_GET_FILTER_FAIL = "LISEREGS_REQUEST_GET_FILTER_FAIL";

export const LISEREGS_REQUEST_GET_BYID = "LISEREGS_REQUEST_GET_BYID";
export const LISEREGS_SUCCESS_GET_BYID = "LISEREGS_SUCCESS_GET_FILTER";
export const LISEREGS_REQUEST_GET_BYID_FAIL = "LISEREGS_REQUEST_GET_BYID_FAIL";

export const LISEREGS_REQUEST_GET_REJECT = "LISEREGS_REQUEST_GET_REJECT";
export const LISEREGS_SUCCESS_GET_REJECT = "LISEREGS_SUCCESS_GET_REJECT";
export const LISEREGS_REQUEST_GET_REJECT_FAIL = "LISEREGS_REQUEST_GET_REJECT_FAIL";

export const NAMERATE_UPDATE_REQUEST = "NAMERATE_UPDATE_REQUEST";
export const NAMERATE_UPDATE_SUCCESS = "NAMERATE_UPDATE_SUCCESS";
export const NAMERATE_UPDATE_FAIL = "NAMERATE_UPDATE_FAIL";

export const DOC_UPDATE_REQUEST = "DOC_UPDATE_REQUEST";
export const DOC_UPDATE_SUCCESS = "DOC_UPDATE_SUCCESS";
export const DOC_UPDATE_FAIL = "DOC_UPDATE_FAIL";

export const APPDETAILS_UPDATE_REQUEST = "APPDETAILS_UPDATE_REQUEST";
export const APPDETAILS_UPDATE_SUCCESS = "APPDETAILS_UPDATE_SUCCESS";
export const APPDETAILS_UPDATE_FAIL = "APPDETAILS_UPDATE_FAIL";

export const EXPENSE_UPDATE_REQUEST = "EXPENSE_UPDATE_REQUEST";
export const EXPENSE_UPDATE_SUCCESS = "EXPENSE_UPDATE_SUCCESS";
export const EXPENSE_UPDATE_FAIL = "EXPENSE_UPDATE_FAIL";

export const LICENSE_UPDATE_REQUEST = "LICENSE_UPDATE_REQUEST";
export const LICENSE_UPDATE_SUCCESS = "LICENSE_UPDATE_SUCCESS";
export const LICENSE_UPDATE_FAIL = "LICENSE_UPDATE_FAIL";

export const INVOICE_UPDATE_REQUEST = "INVOICE_UPDATE_REQUEST";
export const INVOICE_UPDATE_SUCCESS = "INVOICE_UPDATE_SUCCESS";
export const INVOICE_UPDATE_FAIL = "INVOICE_UPDATE_FAIL";

export const COMPANYINFO_UPDATE_REQUEST = "COMPANYINFO_UPDATE_REQUEST";
export const COMPANYINFO_UPDATE_SUCCESS = "COMPANYINFO_UPDATE_SUCCESS";
export const COMPANYINFO_UPDATE_FAIL = "COMPANYINFO_UPDATE_FAIL";

export const ELIBRARY_CREATE_REQUEST = "ELIBRARY_CREATE_REQUEST";
export const ELIBRARY_CREATE_SUCCESS = "ELIBRARY_CREATE_SUCCESS";
export const ELIBRARY_CREATE_FAIL = "ELIBRARY_CREATE_FAIL";

export const ELIBRARY_GET_REQUEST = "ELIBRARY_GET_REQUEST";
export const ELIBRARY_GET_SUCCESS = "ELIBRARY_GET_SUCCESS";
export const ELIBRARY_GET_FAIL = "ELIBRARY_GET_FAIL";

export const ELIBRARY_REQUEST_GET_BYID = "ELIBRARY_REQUEST_GET_BYID";
export const ELIBRARY_SUCCESS_GET_BYID = "ELIBRARY_SUCCESS_GET_BYID";
export const ELIBRARY_REQUEST_GET_BYID_FAIL = "ELIBRARY_REQUEST_GET_BYID_FAIL";

export const ELIBRARY_GET_REQUEST_UPDATE_BY_ID = "ELIBRARY_GET_REQUEST_UPDATE_BY_ID";
export const ELIBRARY_GET_SUCCESS_UPDATE_BY_ID = "ELIBRARY_GET_SUCCESS_UPDATE_BY_ID";
export const ELIBRARY_GET_FAIL_UPDATE_BY_ID = "ELIBRARY_GET_FAIL_UPDATE_BY_ID";

export const ELIBRARY_REQUEST_GET_REJECT = "ELIBRARY_REQUEST_GET_REJECT";
export const ELIBRARY_SUCCESS_GET_REJECT = "ELIBRARY_SUCCESS_GET_REJECT";
export const ELIBRARY_REQUEST_GET_REJECT_FAIL = "ELIBRARY_REQUEST_GET_REJECT_FAIL";

export const ELIBRARY_REQUEST_SAVE_APPROVE = "ELIBRARY_REQUEST_SAVE_APPROVE";
export const ELIBRARY_SUCCESS_SAVE_APPROVE = "ELIBRARY_SUCCESS_SAVE_APPROVE";
export const ELIBRARY_REQUEST_SAVE_APPROVE_FAIL = "ELIBRARY_REQUEST_SAVE_APPROVE_FAIL";

export const ELIBRARY_REQUEST_GET_REJECT_LIST = "ELIBRARY_REQUEST_GET_REJECT_LIST";
export const ELIBRARY_SUCCESS_GET_REJECT_LIST = "ELIBRARY_SUCCESS_GET_REJECT_LIST";
export const ELIBRARY_GET_FAIL_REJECT_LIST = "ELIBRARY_GET_FAIL_REJECT_LIST";

export const AUDIT_REQUEST_OVERDUE_DETAIL_DASHBOARD = "AUDIT_REQUEST_OVERDUE_DETAIL_DASHBOARD";
export const AUDIT_SUCCESS_OVERDUE_DETAIL_DASHBOARD = "AUDIT_SUCCESS_OVERDUE_DETAIL_DASHBOARD";
export const AUDIT_FAIL_OVERDUE_DETAIL_DASHBOARD = "AUDIT_FAIL_OVERDUE_DETAIL_DASHBOARD";

export const COMPANYTAB1_CREATE_REQUEST = "COMPANYTAB1_CREATE_REQUEST";
export const COMPANYTAB1_CREATE_SUCCESS = "COMPANYTAB1_CREATE_SUCCESS";
export const COMPANYTAB1_CREATE_FAIL = "COMPANYTAB1_CREATE_FAIL";

export const COMPANYTAB2_CREATE_REQUEST = "COMPANYTAB2_CREATE_REQUEST";
export const COMPANYTAB2_CREATE_SUCCESS = "COMPANYTAB2_CREATE_SUCCESS";
export const COMPANYTAB2_CREATE_FAIL = "COMPANYTAB2_CREATE_FAIL";

export const COMPANYTAB3_CREATE_REQUEST = "COMPANYTAB3_CREATE_REQUEST";
export const COMPANYTAB3_CREATE_SUCCESS = "COMPANYTAB3_CREATE_SUCCESS";
export const COMPANYTAB3_CREATE_FAIL = "COMPANYTAB3_CREATE_FAIL";

export const COMPANYTAB4_CREATE_REQUEST = "COMPANYTAB4_CREATE_REQUEST";
export const COMPANYTAB4_CREATE_SUCCESS = "COMPANYTAB4_CREATE_SUCCESS";
export const COMPANYTAB4_CREATE_FAIL = "COMPANYTAB4_CREATE_FAIL";

export const COMPANYTAB5_CREATE_REQUEST = "COMPANYTAB5_CREATE_REQUEST";
export const COMPANYTAB5_CREATE_SUCCESS = "COMPANYTAB5_CREATE_SUCCESS";
export const COMPANYTAB5_CREATE_FAIL = "COMPANYTAB5_CREATE_FAIL";

export const COMPANYTAB6_CREATE_REQUEST = "COMPANYTAB6_CREATE_REQUEST";
export const COMPANYTAB6_CREATE_SUCCESS = "COMPANYTAB6_CREATE_SUCCESS";
export const COMPANYTAB6_CREATE_FAIL = "COMPANYTAB6_CREATE_FAIL";

export const COMPANYTAB7_CREATE_REQUEST = "COMPANYTAB7_CREATE_REQUEST";
export const COMPANYTAB7_CREATE_SUCCESS = "COMPANYTAB7_CREATE_SUCCESS";
export const COMPANYTAB7_CREATE_FAIL = "COMPANYTAB7_CREATE_FAIL";

export const COMPANYL_CREATE_REQUEST = "COMPANYL_CREATE_REQUEST";
export const COMPANYL_CREATE_SUCCESS = "COMPANYL_CREATE_SUCCESS";
export const COMPANYL_CREATE_FAIL = "COMPANYL_CREATE_FAIL";

export const COMPANY_GET_TABLE_REQUEST = "COMPANY_GET_TABLE_REQUEST";
export const COMPANY_GET_TABLE_SUCCESS = "COMPANY_GET_TABLE_SUCCESS";
export const COMPANY_GET_TABLE_FAIL = "COMPANY_GET_TABLE_FAIL";

export const COMPANY_REQUEST_GET_BYID = "COMPANY_REQUEST_GET_BYID";
export const COMPANY_SUCCESS_GET_BYID = "COMPANY_SUCCESS_GET_BYID";
export const COMPANY_REQUEST_GET_BYID_FAIL = "COMPANY_REQUEST_GET_BYID_FAIL";

export const COMPANYL_GET_REQUEST = "COMPANYL_GET_REQUEST";
export const COMPANYL_GET_SUCCESS = "COMPANYL_GET_SUCCESS";
export const COMPANYL_GET_FAIL = "COMPANYL_GET_FAIL";

export const COMPANYL_GET_REQUEST_BY_ID = "COMPANYL_GET_REQUEST_BY_ID";
export const COMPANYL_GET_SUCCESS_BY_ID = "COMPANYL_GET_SUCCESS_BY_ID";
export const COMPANYL_GET_FAIL_BY_ID = "COMPANYL_GET_FAIL_BY_ID";

export const COMPANY_LICENSE_REQUEST_GET_APPROVE = "COMPANY_LICENSE_REQUEST_GET_APPROVE";
export const COMPANY_LICENSE_SUCCESS_GET_APPROVE = "COMPANY_LICENSE_SUCCESS_GET_APPROVE";
export const COMPANY_LICENSE_REQUEST_GET_APPROVE_FAIL = "COMPANY_LICENSE_REQUEST_GET_APPROVE_FAIL";

export const COMPANY_LICENSE_REQUEST_GET_FILTER = "COMPANY_LICENSE_REQUEST_GET_FILTER";
export const COMPANY_LICENSE_SUCCESS_GET_FILTER = "COMPANY_LICENSE_SUCCESS_GET_FILTER";
export const COMPANY_LICENSE_GET_FAIL_FILTER = "COMPANY_LICENSE_GET_FAIL_FILTER";

export const COMPANY_REQUEST_SAVE_APPROVE = "COMPANY_REQUEST_SAVE_APPROVE";  /////company save and approve not implemented in backendyet
export const COMPANY_SUCCESS_SAVE_APPROVE = "COMPANY_SUCCESS_SAVE_APPROVE";
export const COMPANY_REQUEST_SAVE_APPROVE_FAIL = "COMPANY_REQUEST_SAVE_APPROVE_FAIL";

export const COMLIANCE_REQUEST_GET_BY_CSID = "COMLIANCE_REQUEST_GET_BY_CSID";
export const COMLIANCE_SUCCESS_GET_BY_CSID = "COMLIANCE_SUCCESS_GET_BY_CSID";
export const COMLIANCE_GET_BY_CSID_FAIL = "COMLIANCE_GET_BY_CSID_FAIL";

export const COMPANY_INERACTION_CREATE_REQUEST = "COMPANY_INERACTION_CREATE_REQUEST";
export const COMPANY_INERACTION_CREATE_SUCCESS = "COMPANY_INERACTION_CREATE_SUCCESS";
export const COMPANY_INERACTION_CREATE_FAIL = "COMPANY_INERACTION_CREATE_FAIL";

export const COMPANY_INTERACTION_REQUEST_GET_BYID = "COMPANY_INTERACTION_REQUEST_GET_BYID";
export const COMPANY_INTERACTION_SUCCESS_GET_BYID = "COMPANY_INTERACTION_SUCCESS_GET_BYID";
export const COMPANY_INTERACTION_FAIL_GET_BYID = "COMPANY_INTERACTION_FAIL_GET_BYID";

export const COMPANY_INTERACTION_REQUEST_UPDATE_BYID = "COMPANY_INTERACTION_REQUEST_UPDATE_BYID";
export const COMPANY_INTERACTION_SUCCESS_UPDATE_BYID = "COMPANY_INTERACTION_SUCCESS_UPDATE_BYID";
export const COMPANY_INTERACTION_FAIL_UPDATE_BYID = "COMPANY_INTERACTION_FAIL_UPDATE_BYID";

export const COMPANY_INTERACTION_GET_TABLE_REQUEST = "COMPANY_INTERACTION_GET_TABLE_REQUEST";
export const COMPANY_INTERACTION_GET_TABLE_SUCCESS = "COMPANY_INTERACTION_GET_TABLE_SUCCESS";
export const COMPANY_INTERACTION_GET_TABLE_FAIL = "COMPANY_INTERACTION_GET_TABLE_FAIL";

export const COMPANY_PROFILE_INERACTION_REQUEST_GET_APPROVE = "COMPANY_PROFILE_INERACTION_REQUEST_GET_APPROVE";
export const COMPANY_PROFILE_INERACTION_SUCCESS_GET_APPROVE = "COMPANY_INTERACTION_GET_TABLE_SUCCESS";
export const COMPANY_PROFILE_INERACTION_REQUEST_GET_APPROVE_FAIL = "COMPANY_PROFILE_INERACTION_REQUEST_GET_APPROVE_FAIL";

export const COMPANY_INTERACT_REQUEST_GET_FILTER = "COMPANY_INTERACT_REQUEST_GET_FILTER";
export const COMPANY_INTERACT_SUCCESS_GET_FILTER = "COMPANY_INTERACT_SUCCESS_GET_FILTER";
export const COMPANY_INTERACT_GET_FAIL_FILTER = "COMPANY_INTERACT_GET_FAIL_FILTER";

export const COMPANY_INTERACTION_LICENSE_GET_REQUEST = "COMPANY_INTERACTION_LICENSE_GET_REQUEST";
export const COMPANY_INTERACTION_LICENSE_GET_SUCCESS = "COMPANY_INTERACTION_LICENSE_GET_SUCCESS";
export const COMPANY_INTERACTION_LICENSE_CREATE_FAIL = "COMPANY_INTERACTION_LICENSE_CREATE_FAIL";

export const COMPANY_INTERACTION_LIC_CREATE_REQUEST = "COMPANY_INTERACTION_LIC_CREATE_REQUEST";
export const COMPANY_INTERACTION_LIC_CREATE_SUCCESS = "COMPANY_INTERACTION_LIC_CREATE_SUCCESS";
export const COMPANY_INTERACTION_LIC_CREATE_FAIL = "COMPANY_INTERACTION_LIC_CREATE_FAIL";


export const COMPANY_INTERACTION_LIC_REQUEST_GET_BYID = "COMPANY_INTERACTION_LIC_REQUEST_GET_BYID";
export const COMPANY_INTERACTION_LIC_SUCCESS_GET_BYID = "COMPANY_INTERACTION_LIC_SUCCESS_GET_BYID";
export const COMPANY_INTERACTION_LIC_FAIL_GET_BYID = "COMPANY_INTERACTION_LIC_FAIL_GET_BYID";

export const COMPANY_INTERACTION_LIC_REQUEST_UPDATE_BYID = "COMPANY_INTERACTION_LIC_REQUEST_UPDATE_BYID";
export const COMPANY_INTERACTION_LIC_SUCCESS_UPDATE_BYID = "COMPANY_INTERACTION_LIC_CREATE_SUCCESS";
export const COMPANY_INTERACTION_LIC_FAIL_UPDATE_BYID = "COMPANY_INTERACTION_LIC_FAIL_UPDATE_BYID";

export const COMPANY_LICENSE_INERACTION_REQUEST_GET_APPROVE = "COMPANY_LICENSE_INERACTION_REQUEST_GET_APPROVE";
export const COMPANY_LICENSE_INERACTION_SUCCESS_GET_APPROVE = "COMPANY_LICENSE_INERACTION_SUCCESS_GET_APPROVE";
export const COMPANY_LICENSE_INERACTION_REQUEST_GET_APPROVE_FAIL = "COMPANY_LICENSE_INERACTION_REQUEST_GET_APPROVE_FAIL";

export const COMPANY_LICENSE_INTERACT_REQUEST_GET_FILTER = "COMPANY_LICENSE_INTERACT_REQUEST_GET_FILTER";
export const COMPANY_LICENSE_INTERACT_SUCCESS_GET_FILTER = "COMPANY_LICENSE_INTERACT_SUCCESS_GET_FILTER";
export const COMPANY_LICENSE_INTERACT_GET_FAIL_FILTER = "COMPANY_LICENSE_INTERACT_GET_FAIL_FILTER"

export const COMPANY_ASSIGN_CREATE_REQUEST = "COMPANY_ASSIGN_CREATE_REQUEST";
export const COMPANY_ASSIGN_CREATE_SUCCESS = "COMPANY_ASSIGN_CREATE_SUCCESS";
export const COMPANY_ASSIGN_CREATE_FAIL = "COMPANY_ASSIGN_CREATE_FAIL";

export const COMPANY_ASSIGNREQUEST_GET_BYID = "COMPANY_ASSIGNREQUEST_GET_BYID";
export const COMPANY_ASSIGNSUCCESS_GET_BYID = "COMPANY_ASSIGNSUCCESS_GET_BYID";
export const COMPANY_ASSIGNFAIL_GET_BYID = "COMPANY_ASSIGNFAIL_GET_BYID";

export const COMPANY_ASSIGN_REQUEST_UPDATE_BYID = "COMPANY_ASSIGN_REQUEST_UPDATE_BYID";
export const COMPANY_ASSIGN_SUCCESS_UPDATE_BYID = "COMPANY_ASSIGN_SUCCESS_UPDATE_BYID";
export const COMPANY_ASSIGN_FAIL_UPDATE_BYID = "COMPANY_ASSIGN_FAIL_UPDATE_BYID";

export const COMPANY_ASSIGN_GET_REQUEST = "COMPANY_ASSIGN_GET_REQUEST";
export const COMPANY_ASSIGN_GET_SUCCESS = "COMPANY_ASSIGN_GET_SUCCESS";
export const COMPANY_ASSIGN_TABLE_FAIL = "COMPANY_ASSIGN_TABLE_FAIL";

export const COMPANY_ASSIGN_ON_CREATE_GET_REQUEST = "COMPANY_ASSIGN_ON_CREATE_GET_REQUEST";
export const COMPANY_ASSIGN_ON_CREATE_GET_SUCCESS = "COMPANY_ASSIGN_ON_CREATE_GET_SUCCESS";
export const COMPANY_ASSIGN_ON_CREATE_CREATE_FAIL = "COMPANY_ASSIGN_ON_CREATE_CREATE_FAIL";

export const COMPANY_ASSIGN_REQUEST_GET_FILTER = "COMPANY_ASSIGN_REQUEST_GET_FILTER";
export const COMPANY_ASSIGN_SUCCESS_GET_FILTER = "COMPANY_ASSIGN_SUCCESS_GET_FILTER";
export const COMPANY_ASSIGN_GET_FAIL_FILTER = "COMPANY_ASSIGN_GET_FAIL_FILTER";

export const COMPANY_ASSIGNA_REQUEST_GET_FILTER = "COMPANY_ASSIGNA_REQUEST_GET_FILTER";
export const COMPANY_ASSIGNA_SUCCESS_GET_FILTER = "COMPANY_ASSIGNA_SUCCESS_GET_FILTER";
export const COMPANY_ASSIGNA_GET_FAIL_FILTER = "COMPANY_ASSIGNA_GET_FAIL_FILTER";

// src/redux/actionTypes.js
export const CHECKLIST_ADD_IN_AUDIT_REQUEST = 'CHECKLIST_ADD_IN_AUDIT_REQUEST';
export const CHECKLIST_ADD_IN_AUDIT_SUCCESS = 'CHECKLIST_ADD_IN_AUDIT_SUCCESS';
export const CHECKLIST_ADD_IN_AUDIT_FAILURE = 'CHECKLIST_ADD_IN_AUDIT_FAILURE';

export const FILE_UPLOADS_REQUEST = 'FILE_UPLOADS_REQUEST';
export const FILE_UPLOADS_SUCCESS = 'FILE_UPLOADS_SUCCESS';
export const FILE_UPLOADS_FAIL = 'FILE_UPLOADS_FAIL';


export const AUDIT_UPLOAD_STATUS_REQUEST = 'AUDIT_UPLOAD_STATUS_REQUEST';
export const AUDIT_UPLOAD_STATUS_SUCCESS = 'AUDIT_UPLOAD_STATUS_SUCCESS';
export const AUDIT_UPLOAD_STATUS_FAILURE = 'AUDIT_UPLOAD_STATUS_FAILURE';


export const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';

export const UPDATE_AUDIT_FIELDS_REQUEST = 'UPDATE_AUDIT_FIELDS_REQUEST';
export const UPDATE_AUDIT_FIELDS_SUCCESS = 'UPDATE_AUDIT_FIELDS_SUCCESS';
export const UPDATE_AUDIT_FIELDS_FAILURE = 'UPDATE_AUDIT_FIELDS_FAILURE';

export const UPDATE_DUE_DATES_REQUEST = 'UPDATE_DUE_DATES_REQUEST';
export const UPDATE_DUE_DATES_SUCCESS = 'UPDATE_DUE_DATES_SUCCESS';
export const UPDATE_DUE_DATES_FAILURE = 'UPDATE_DUE_DATES_FAILURE';

export const BRANCHES_ADD_REQUEST = 'BRANCHES_ADD_REQUEST';
export const BRANCHES_ADD_SUCCESS = 'BRANCHES_ADD_SUCCESS';
export const BRANCHES_ADD_FAILURE = 'BRANCHES_ADD_FAILURE';



export const BRANCHES_GET_REQUEST = 'BRANCHES_GET_REQUEST';
export const BRANCHES_GET_SUCCESS = 'BRANCHES_GET_SUCCESS';
export const BRANCHES_GET_FAIL = 'BRANCHES_GET_FAIL';


export const BRANCHES_TABLE_GET_REQUEST = 'BRANCHES_TABLE_GET_REQUEST';
export const BRANCHES_TABLE_GET_SUCCESS = 'BRANCHES_TABLE_GET_SUCCESS';
export const BRANCHES_TABLE_GET_FAIL = 'BRANCHES_TABLE_GET_FAIL';


export const BRANCHES_EDIT_REQUEST = 'BRANCHES_EDIT_REQUEST';
export const BRANCHES_EDIT_SUCCESS = 'BRANCHES_EDIT_SUCCESS';
export const BRANCHES_EDIT_FAILURE = 'BRANCHES_EDIT_FAILURE';


export const BRANCHES_GET_BY_ID_REQUEST = 'BRANCHES_GET_BY_ID_REQUEST';
export const BRANCHES_GET_BY_ID_SUCCESS = 'BRANCHES_GET_BY_ID_SUCCESS';
export const BRANCHES_GET_BY_ID_FAILURE = 'BRANCHES_GET_BY_ID_FAILURE';


export const COMPANY_BRANCHES_GET_REQUEST = 'COMPANY_BRANCHES_GET_REQUEST';
export const COMPANY_BRANCHES_GET_SUCCESS = 'COMPANY_BRANCHES_GET_SUCCESS';
export const COMPANY_BRANCHES_GET_FAIL = 'COMPANY_BRANCHES_GET_FAIL';


export const COMPANY_BRANCHES_BY_CREATE_REQUEST = 'COMPANY_BRANCHES_BY_CREATE_REQUEST';
export const COMPANY_BRANCHES_BY_CREATE_SUCCESS = 'COMPANY_BRANCHES_BY_CREATE_SUCCESS';
export const COMPANY_BRANCHES_BY_CREATE_FAIL = 'COMPANY_BRANCHES_BY_CREATE_FAIL';

export const NOTICE_ADD_REQUEST = 'NOTICE_ADD_REQUEST';
export const NOTICE_ADD_SUCCESS = 'NOTICE_ADD_SUCCESS';
export const NOTICE_ADD_FAILURE = 'NOTICE_ADD_FAILURE';

export const NOTICES_TABLE_GET_REQUEST = 'NOTICES_TABLE_GET_REQUEST';
export const NOTICES_TABLE_GET_SUCCESS = 'NOTICES_TABLE_GET_SUCCESS';
export const NOTICES_TABLE_GET_FAIL = 'NOTICES_TABLE_GET_FAIL';


export const NOTICES_EDIT_REQUEST = 'NOTICES_EDIT_REQUEST';
export const NOTICES_EDIT_SUCCESS = 'NOTICES_EDIT_SUCCESS';
export const NOTICES_EDIT_FAILURE = 'NOTICES_EDIT_FAILURE';

export const NOTICES_DELETE_REQUEST = 'NOTICES_DELETE_REQUEST';
export const NOTICES_DELETE_SUCCESS = 'NOTICES_DELETE_SUCCESS';
export const NOTICES_DELETE_FAILURE = 'NOTICES_DELETE_FAILURE';


export const NOTICES_GET_BY_ID_REQUEST = 'NOTICES_GET_BY_ID_REQUEST';
export const NOTICES_GET_BY_ID_SUCCESS = 'NOTICES_GET_BY_ID_SUCCESS';
export const NOTICES_GET_BY_ID_FAILURE = 'NOTICES_GET_BY_ID_FAILURE';

export const LABOUR_AGREEMENT_NAME_GET_REQUEST = 'LABOUR_AGREEMENT_NAME_GET_REQUEST';
export const LABOUR_AGREEMENT_NAME_GET_SUCCESS = 'LABOUR_AGREEMENT_NAME_GET_SUCCESS';
export const LABOUR_AGREEMENT_NAME_GET_FAIL = 'LABOUR_AGREEMENT_NAME_GET_FAIL';

export const PRINCIPLE_AGREEMENT_NAME_GET_REQUEST = 'PRINCIPLE_AGREEMENT_NAME_GET_REQUEST';
export const PRINCIPLE_AGREEMENT_NAME_GET_SUCCESS = 'PRINCIPLE_AGREEMENT_NAME_GET_SUCCESS';
export const PRINCIPLE_AGREEMENT_NAME_GET_FAIL = 'PRINCIPLE_AGREEMENT_NAME_GET_FAIL';

export const AUDIT_LCA_REQUEST_All_DETAIL = "AUDIT_LCA_REQUEST_All_DETAIL";
export const AUDIT_LCA_SUCCESS_All_DETAIL = "AUDIT_LCA_SUCCESS_All_DETAIL";
export const AUDIT_LCA_FAIL_All_DETAIL = "AUDIT_LCA_FAIL_All_DETAIL";

export const AUDIT_PA_REQUEST_All_DETAIL = "AUDIT_PA_REQUEST_All_DETAIL";
export const AUDIT_PA_SUCCESS_All_DETAIL = "AUDIT_PA_SUCCESS_All_DETAIL";
export const AUDIT_PA_FAIL_All_DETAIL = "AUDIT_PA_FAIL_All_DETAIL";

export const CATEGORY_COMPLIANCE_REQUEST_GET = 'CATEGORY_COMPLIANCE_REQUEST_GET';
export const CATEGORY_COMPLIANCE_SUCCESS_GET = 'CATEGORY_COMPLIANCE_SUCCESS_GET';
export const CATEGORY_COMPLIANCE_GET_FAIL = 'CATEGORY_COMPLIANCE_GET_FAIL';

export const AUDITOR_LCA_REQUEST_GET_ALL_FILTER = 'AUDITOR_LCA_REQUEST_GET_ALL_FILTER';
export const AUDITOR_LCA_SUCCESS_GET_ALL_FILTER = 'AUDITOR_LCA_SUCCESS_GET_ALL_FILTER';
export const AUDITOR_LCA_GET_FAIL_ALL_FILTER = 'AUDITOR_LCA_GET_FAIL_ALL_FILTER';

export const AUDITOR_PA_REQUEST_GET_ALL_FILTER = 'AUDITOR_PA_REQUEST_GET_ALL_FILTER';
export const AUDITOR_PA_SUCCESS_GET_ALL_FILTER = 'AUDITOR_PA_SUCCESS_GET_ALL_FILTER';
export const AUDITOR_PA_GET_FAIL_ALL_FILTER = 'AUDITOR_PA_GET_FAIL_ALL_FILTER';

export const AUDIT_UPLOAD_STATUS_REQUEST_LCA = 'AUDIT_UPLOAD_STATUS_REQUEST_LCA';
export const AUDIT_UPLOAD_STATUS_SUCCESS_LCA = 'AUDIT_UPLOAD_STATUS_SUCCESS_LCA';
export const AUDIT_UPLOAD_STATUS_FAILURE_LCA = 'AUDIT_UPLOAD_STATUS_FAILURE_LCA';

export const AUDIT_UPLOAD_STATUS_REQUEST_PA = 'AUDIT_UPLOAD_STATUS_REQUEST_PA';
export const AUDIT_UPLOAD_STATUS_SUCCESS_PA = 'AUDIT_UPLOAD_STATUS_SUCCESS_PA';
export const AUDIT_UPLOAD_STATUS_FAILURE_PA = 'AUDIT_UPLOAD_STATUS_FAILURE_PA';

export const FILE_UPLOADS_REQUEST_LCA = 'FILE_UPLOADS_REQUEST_LCA';
export const FILE_UPLOADS_SUCCESS_LCA = 'FILE_UPLOADS_SUCCESS_LCA';
export const FILE_UPLOADS_FAIL_LCA = 'FILE_UPLOADS_FAIL_LCA';

export const FILE_UPLOADS_REQUEST_PA = 'FILE_UPLOADS_REQUEST_PA';
export const FILE_UPLOADS_SUCCESS_PA = 'FILE_UPLOADS_SUCCESS_PA';
export const FILE_UPLOADS_FAIL_PA = 'FILE_UPLOADS_FAIL_PA';

//elibrary

export const ACT_LIBRARY_CREATE_REQUEST = 'ACT_LIBRARY_CREATE_REQUEST';
export const ACT_LIBRARY_CREATE_SUCCESS = 'ACT_LIBRARY_CREATE_SUCCESS';
export const ACT_LIBRARY_CREATE_FAILURE = 'ACT_LIBRARY_CREATE_FAILURE';

export const ACT_LIBRARY_GET_REQUEST = 'ACT_LIBRARY_GET_REQUEST';
export const ACT_LIBRARY_GET_SUCCESS = 'ACT_LIBRARY_GET_SUCCESS';
export const ACT_LIBRARY_GET_FAILURE = 'ACT_LIBRARY_GET_FAILURE';

export const ACT_LIBRARY_EDIT_REQUEST = 'ACT_LIBRARY_EDIT_REQUEST';
export const ACT_LIBRARY_EDIT_SUCCESS = 'ACT_LIBRARY_EDIT_SUCCESS';
export const ACT_LIBRARY_EDIT_FAILURE = 'ACT_LIBRARY_EDIT_FAILURE';

export const ACT_LIBRARY_DELETE_REQUEST = 'ACT_LIBRARY_DELETE_REQUEST';
export const ACT_LIBRARY_DELETE_SUCCESS = 'ACT_LIBRARY_DELETE_SUCCESS';
export const ACT_LIBRARY_DELETE_FAILURE = 'ACT_LIBRARY_DELETE_FAILURE';


export const RULE_LIBRARY_CREATE_REQUEST = 'RULE_LIBRARY_CREATE_REQUEST';
export const RULE_LIBRARY_CREATE_SUCCESS = 'RULE_LIBRARY_CREATE_SUCCESS';
export const RULE_LIBRARY_CREATE_FAILURE = 'RULE_LIBRARY_CREATE_FAILURE';

export const RULE_LIBRARY_GET_REQUEST = 'RULE_LIBRARY_GET_REQUEST';
export const RULE_LIBRARY_GET_SUCCESS = 'RULE_LIBRARY_GET_SUCCESS';
export const RULE_LIBRARY_GET_FAILURE = 'RULE_LIBRARY_GET_FAILURE';

export const RULE_LIBRARY_EDIT_REQUEST = 'RULE_LIBRARY_EDIT_REQUEST';
export const RULE_LIBRARY_EDIT_SUCCESS = 'RULE_LIBRARY_EDIT_SUCCESS';
export const RULE_LIBRARY_EDIT_FAILURE = 'RULE_LIBRARY_EDIT_FAILURE';

export const RULE_LIBRARY_DELETE_REQUEST = 'RULE_LIBRARY_DELETE_REQUEST';
export const RULE_LIBRARY_DELETE_SUCCESS = 'RULE_LIBRARY_DELETE_SUCCESS';
export const RULE_LIBRARY_DELETE_FAILURE = 'RULE_LIBRARY_DELETE_FAILURE';


export const LABOUR_FORMS_LIBRARY_CREATE_REQUEST = 'LABOUR_FORMS_LIBRARY_CREATE_REQUEST';
export const LABOUR_FORMS_LIBRARY_CREATE_SUCCESS = 'LABOUR_FORMS_LIBRARY_CREATE_SUCCESS';
export const LABOUR_FORMS_LIBRARY_CREATE_FAILURE = 'LABOUR_FORMS_LIBRARY_CREATE_FAILURE';

export const LABOUR_FORMS_LIBRARY_GET_REQUEST = 'LABOUR_FORMS_LIBRARY_GET_REQUEST';
export const LABOUR_FORMS_LIBRARY_GET_SUCCESS = 'LABOUR_FORMS_LIBRARY_GET_SUCCESS';
export const LABOUR_FORMS_LIBRARY_GET_FAILURE = 'LABOUR_FORMS_LIBRARY_GET_FAILURE';

export const LABOUR_FORMS_LIBRARY_EDIT_REQUEST = 'LABOUR_FORMS_LIBRARY_EDIT_REQUEST';
export const LABOUR_FORMS_LIBRARY_EDIT_SUCCESS = 'LABOUR_FORMS_LIBRARY_EDIT_SUCCESS';
export const LABOUR_FORMS_LIBRARY_EDIT_FAILURE = 'LABOUR_FORMS_LIBRARY_EDIT_FAILURE';

export const LABOUR_FORMS_LIBRARY_DELETE_REQUEST = 'LABOUR_FORMS_LIBRARY_DELETE_REQUEST';
export const LABOUR_FORMS_LIBRARY_DELETE_SUCCESS = 'LABOUR_FORMS_LIBRARY_DELETE_SUCCESS';
export const LABOUR_FORMS_LIBRARY_DELETE_FAILURE = 'LABOUR_FORMS_LIBRARY_DELETE_FAILURE';


export const HOLIDAY_LIBRARY_CREATE_REQUEST = 'HOLIDAY_LIBRARY_CREATE_REQUEST';
export const HOLIDAY_LIBRARY_CREATE_SUCCESS = 'HOLIDAY_LIBRARY_CREATE_SUCCESS';
export const HOLIDAY_LIBRARY_CREATE_FAILURE = 'HOLIDAY_LIBRARY_CREATE_FAILURE';

export const HOLIDAY_LIBRARY_GET_REQUEST = 'HOLIDAY_LIBRARY_GET_REQUEST';
export const HOLIDAY_LIBRARY_GET_SUCCESS = 'HOLIDAY_LIBRARY_GET_SUCCESS';
export const HOLIDAY_LIBRARY_GET_FAILURE = 'HOLIDAY_LIBRARY_GET_FAILURE';

export const HOLIDAY_LIBRARY_GET_REQUEST1 = 'HOLIDAY_LIBRARY_GET_REQUEST1';
export const HOLIDAY_LIBRARY_GET_SUCCESS1 = 'HOLIDAY_LIBRARY_GET_SUCCESS1';
export const HOLIDAY_LIBRARY_GET_FAILURE1 = 'HOLIDAY_LIBRARY_GET_FAILURE1';

export const HOLIDAY_LIBRARY_EDIT_REQUEST = 'HOLIDAY_LIBRARY_EDIT_REQUEST';
export const HOLIDAY_LIBRARY_EDIT_SUCCESS = 'HOLIDAY_LIBRARY_EDIT_SUCCESS';
export const HOLIDAY_LIBRARY_EDIT_FAILURE = 'HOLIDAY_LIBRARY_EDIT_FAILURE';

export const HOLIDAY_LIBRARY_DELETE_REQUEST = 'HOLIDAY_LIBRARY_DELETE_REQUEST';
export const HOLIDAY_LIBRARY_DELETE_SUCCESS = 'HOLIDAY_LIBRARY_DELETE_SUCCESS';
export const HOLIDAY_LIBRARY_DELETE_FAILURE = 'HOLIDAY_LIBRARY_DELETE_FAILURE';


export const LABOUR_WELFARE_LIBRARY_CREATE_REQUEST = 'LABOUR_WELFARE_LIBRARY_CREATE_REQUEST';
export const LABOUR_WELFARE_LIBRARY_CREATE_SUCCESS = 'LABOUR_WELFARE_LIBRARY_CREATE_SUCCESS';
export const LABOUR_WELFARE_LIBRARY_CREATE_FAILURE = 'LABOUR_WELFARE_LIBRARY_CREATE_FAILURE';

export const LABOUR_WELFARE_LIBRARY_GET_REQUEST = 'LABOUR_WELFARE_LIBRARY_GET_REQUEST';
export const LABOUR_WELFARE_LIBRARY_GET_SUCCESS = 'LABOUR_WELFARE_LIBRARY_GET_SUCCESS';
export const LABOUR_WELFARE_LIBRARY_GET_FAILURE = 'LABOUR_WELFARE_LIBRARY_GET_FAILURE';

export const LABOUR_WELFARE_LIBRARY_EDIT_REQUEST = 'LABOUR_WELFARE_LIBRARY_EDIT_REQUEST';
export const LABOUR_WELFARE_LIBRARY_EDIT_SUCCESS = 'LABOUR_WELFARE_LIBRARY_EDIT_SUCCESS';
export const LABOUR_WELFARE_LIBRARY_EDIT_FAILURE = 'LABOUR_WELFARE_LIBRARY_EDIT_FAILURE';

export const LABOUR_WELFARE_LIBRARY_DELETE_REQUEST = 'LABOUR_WELFARE_LIBRARY_DELETE_REQUEST';
export const LABOUR_WELFARE_LIBRARY_DELETE_SUCCESS = 'LABOUR_WELFARE_LIBRARY_DELETE_SUCCESS';
export const LABOUR_WELFARE_LIBRARY_DELETE_FAILURE = 'LABOUR_WELFARE_LIBRARY_DELETE_FAILURE';


export const MINIMUM_WAGE_LIBRARY_CREATE_REQUEST = 'MINIMUM_WAGE_LIBRARY_CREATE_REQUEST';
export const MINIMUM_WAGE_LIBRARY_CREATE_SUCCESS = 'MINIMUM_WAGE_LIBRARY_CREATE_SUCCESS';
export const MINIMUM_WAGE_LIBRARY_CREATE_FAILURE = 'MINIMUM_WAGE_LIBRARY_CREATE_FAILURE';

export const MINIMUM_WAGE_LIBRARY_GET_REQUEST = 'MINIMUM_WAGE_LIBRARY_GET_REQUEST';
export const MINIMUM_WAGE_LIBRARY_GET_SUCCESS = 'MINIMUM_WAGE_LIBRARY_GET_SUCCESS';
export const MINIMUM_WAGE_LIBRARY_GET_FAILURE = 'MINIMUM_WAGE_LIBRARY_GET_FAILURE';

export const MINIMUM_WAGE_LIBRARY_EDIT_REQUEST = 'MINIMUM_WAGE_LIBRARY_EDIT_REQUEST';
export const MINIMUM_WAGE_LIBRARY_EDIT_SUCCESS = 'MINIMUM_WAGE_LIBRARY_EDIT_SUCCESS';
export const MINIMUM_WAGE_LIBRARY_EDIT_FAILURE = 'MINIMUM_WAGE_LIBRARY_EDIT_FAILURE';

export const MINIMUM_WAGE_LIBRARY_DELETE_REQUEST = 'MINIMUM_WAGE_LIBRARY_DELETE_REQUEST';
export const MINIMUM_WAGE_LIBRARY_DELETE_SUCCESS = 'MINIMUM_WAGE_LIBRARY_DELETE_SUCCESS';
export const MINIMUM_WAGE_LIBRARY_DELETE_FAILURE = 'MINIMUM_WAGE_LIBRARY_DELETE_FAILURE';


export const WH_LR_LIBRARY_CREATE_REQUEST = 'WH_LR_LIBRARY_CREATE_REQUEST';
export const WH_LR_LIBRARY_CREATE_SUCCESS = 'WH_LR_LIBRARY_CREATE_SUCCESS';
export const WH_LR_LIBRARY_CREATE_FAILURE = 'WH_LR_LIBRARY_CREATE_FAILURE';

export const WH_LR_LIBRARY_GET_REQUEST = 'WH_LR_LIBRARY_GET_REQUEST';
export const WH_LR_LIBRARY_GET_SUCCESS = 'WH_LR_LIBRARY_GET_SUCCESS';
export const WH_LR_LIBRARY_GET_FAILURE = 'WH_LR_LIBRARY_GET_FAILURE';

export const WH_LR_LIBRARY_EDIT_REQUEST = 'WH_LR_LIBRARY_EDIT_REQUEST';
export const WH_LR_LIBRARY_EDIT_SUCCESS = 'WH_LR_LIBRARY_EDIT_SUCCESS';
export const WH_LR_LIBRARY_EDIT_FAILURE = 'WH_LR_LIBRARY_EDIT_FAILURE';

export const WH_LR_LIBRARY_DELETE_REQUEST = 'WH_LR_LIBRARY_DELETE_REQUEST';
export const WH_LR_LIBRARY_DELETE_SUCCESS = 'WH_LR_LIBRARY_DELETE_SUCCESS';
export const WH_LR_LIBRARY_DELETE_FAILURE = 'WH_LR_LIBRARY_DELETE_FAILURE';


export const PT_LIBRARY_CREATE_REQUEST = 'PT_LIBRARY_CREATE_REQUEST';
export const PT_LIBRARY_CREATE_SUCCESS = 'PT_LIBRARY_CREATE_SUCCESS';
export const PT_LIBRARY_CREATE_FAILURE = 'PT_LIBRARY_CREATE_FAILURE';

export const PT_LIBRARY_GET_REQUEST = 'PT_LIBRARY_GET_REQUEST';
export const PT_LIBRARY_GET_SUCCESS = 'PT_LIBRARY_GET_SUCCESS';
export const PT_LIBRARY_GET_FAILURE = 'PT_LIBRARY_GET_FAILURE';

export const PT_LIBRARY_EDIT_REQUEST = 'PT_LIBRARY_EDIT_REQUEST';
export const PT_LIBRARY_EDIT_SUCCESS = 'PT_LIBRARY_EDIT_SUCCESS';
export const PT_LIBRARY_EDIT_FAILURE = 'PT_LIBRARY_EDIT_FAILURE';

export const PT_LIBRARY_DELETE_REQUEST = 'PT_LIBRARY_DELETE_REQUEST';
export const PT_LIBRARY_DELETE_SUCCESS = 'PT_LIBRARY_DELETE_SUCCESS';
export const PT_LIBRARY_DELETE_FAILURE = 'PT_LIBRARY_DELETE_FAILURE';


export const COMP_CAT_CREATE_REQUEST = 'COMP_CAT_CREATE_REQUEST';
export const COMP_CAT_CREATE_SUCCESS = 'COMP_CAT_CREATE_SUCCESS';
export const COMP_CAT_CREATE_FAILURE = 'COMP_CAT_CREATE_FAILURE';

export const COMP_CAT_GET_REQUEST = 'COMP_CAT_GET_REQUEST';
export const COMP_CAT_GET_SUCCESS = 'COMP_CAT_GET_SUCCESS';
export const COMP_CAT_GET_FAILURE = 'COMP_CAT_GET_FAILURE';

export const COMP_LIST_CAT_GET_REQUEST = 'COMP_LIST_CAT_GET_REQUEST';
export const COMP_LIST_CAT_GET_SUCCESS = 'COMP_LIST_CAT_GET_SUCCESS';
export const COMP_LIST_CAT_GET_FAILURE = 'COMP_LIST_CAT_GET_FAILURE';

export const COMP_CAT_EDIT_REQUEST = 'COMP_CAT_EDIT_REQUEST';
export const COMP_CAT_EDIT_SUCCESS = 'COMP_CAT_EDIT_SUCCESS';
export const COMP_CAT_EDIT_FAILURE = 'COMP_CAT_EDIT_FAILURE';

export const COMP_CAT_DELETE_REQUEST = 'COMP_CAT_DELETE_REQUEST';
export const COMP_CAT_DELETE_SUCCESS = 'COMP_CAT_DELETE_SUCCESS';
export const COMP_CAT_DELETE_FAILURE = 'COMP_CAT_DELETE_FAILURE';

export const COMP_Q_A_CREATE_REQUEST = 'COMP_Q_A_CREATE_REQUEST';
export const COMP_Q_A_CREATE_SUCCESS = 'COMP_Q_A_CREATE_SUCCESS';
export const COMP_Q_A_CREATE_FAILURE = 'COMP_Q_A_CREATE_FAILURE';

export const COMP_Q_A_GET_REQUEST = 'COMP_Q_A_GET_REQUEST';
export const COMP_Q_A_GET_SUCCESS = 'COMP_Q_A_GET_SUCCESS';
export const COMP_Q_A_GET_FAILURE = 'COMP_Q_A_GET_FAILURE';

export const COMP_Q_A_EDIT_REQUEST = 'COMP_Q_A_EDIT_REQUEST';
export const COMP_Q_A_EDIT_SUCCESS = 'COMP_Q_A_EDIT_SUCCESS';
export const COMP_Q_A_EDIT_FAILURE = 'COMP_Q_A_EDIT_FAILURE';

export const COMP_Q_A_DELETE_REQUEST = 'COMP_Q_A_DELETE_REQUEST';
export const COMP_Q_A_DELETE_SUCCESS = 'COMP_Q_A_DELETE_SUCCESS';
export const COMP_Q_A_DELETE_FAILURE = 'COMP_Q_A_DELETE_FAILURE';


export const POLICY_TEMPLATE_CREATE_REQUEST = 'POLICY_TEMPLATE_CREATE_REQUEST';
export const POLICY_TEMPLATE_CREATE_SUCCESS = 'POLICY_TEMPLATE_CREATE_SUCCESS';
export const POLICY_TEMPLATE_CREATE_FAILURE = 'POLICY_TEMPLATE_CREATE_FAILURE';

export const POLICY_TEMPLATE_GET_REQUEST = 'POLICY_TEMPLATE_GET_REQUEST';
export const POLICY_TEMPLATE_GET_SUCCESS = 'POLICY_TEMPLATE_GET_SUCCESS';
export const POLICY_TEMPLATE_GET_FAILURE = 'POLICY_TEMPLATE_GET_FAILURE';

export const POLICY_TEMPLATE_EDIT_REQUEST = 'POLICY_TEMPLATE_EDIT_REQUEST';
export const POLICY_TEMPLATE_EDIT_SUCCESS = 'POLICY_TEMPLATE_EDIT_SUCCESS';
export const POLICY_TEMPLATE_EDIT_FAILURE = 'POLICY_TEMPLATE_EDIT_FAILURE';

export const POLICY_TEMPLATE_DELETE_REQUEST = 'POLICY_TEMPLATE_DELETE_REQUEST';
export const POLICY_TEMPLATE_DELETE_SUCCESS = 'POLICY_TEMPLATE_DELETE_SUCCESS';
export const POLICY_TEMPLATE_DELETE_FAILURE = 'POLICY_TEMPLATE_DELETE_FAILURE';


export const RE_LEGAL_CREATE_REQUEST = 'RE_LEGAL_CREATE_REQUEST';
export const RE_LEGAL_CREATE_SUCCESS = 'RE_LEGAL_CREATE_SUCCESS';
export const RE_LEGAL_CREATE_FAILURE = 'RE_LEGAL_CREATE_FAILURE';

export const RE_LEGAL_GET_REQUEST = 'RE_LEGAL_GET_REQUEST';
export const RE_LEGAL_GET_SUCCESS = 'RE_LEGAL_GET_SUCCESS';
export const RE_LEGAL_GET_FAILURE = 'RE_LEGAL_GET_FAILURE';

export const RE_LEGAL_EDIT_REQUEST = 'RE_LEGAL_EDIT_REQUEST';
export const RE_LEGAL_EDIT_SUCCESS = 'RE_LEGAL_EDIT_SUCCESS';
export const RE_LEGAL_EDIT_FAILURE = 'RE_LEGAL_EDIT_FAILURE';

export const RE_LEGAL_DELETE_REQUEST = 'RE_LEGAL_DELETE_REQUEST';
export const RE_LEGAL_DELETE_SUCCESS = 'RE_LEGAL_DELETE_SUCCESS';
export const RE_LEGAL_DELETE_FAILURE = 'RE_LEGAL_DELETE_FAILURE';



export const GENERAL_CREATE_REQUEST = 'GENERAL_CREATE_REQUEST';
export const GENERAL_CREATE_SUCCESS = 'GENERAL_CREATE_SUCCESS';
export const GENERAL_CREATE_FAILURE = 'GENERAL_CREATE_FAILURE';

export const GENERAL_GET_REQUEST = 'GENERAL_GET_REQUEST';
export const GENERAL_GET_SUCCESS = 'GENERAL_GET_SUCCESS';
export const GENERAL_GET_FAILURE = 'GENERAL_GET_FAILURE';

export const GENERAL_EDIT_REQUEST = 'GENERAL_EDIT_REQUEST';
export const GENERAL_EDIT_SUCCESS = 'GENERAL_EDIT_SUCCESS';
export const GENERAL_EDIT_FAILURE = 'GENERAL_EDIT_FAILURE';

export const GENERAL_DELETE_REQUEST = 'GENERAL_DELETE_REQUEST';
export const GENERAL_DELETE_SUCCESS = 'GENERAL_DELETE_SUCCESS';
export const GENERAL_DELETE_FAILURE = 'GENERAL_DELETE_FAILURE';

export const HELP_MAIL_REQUEST = ' HELP_MAIL_REQUEST';
export const HELP_MAIL_SUCCESS = ' HELP_MAIL_SUCCESS';
export const HELP_MAIL_FAILURE = ' HELP_MAIL_FAILURE';

export const HOLIDAY_STATE_GET_REQUEST = ' HOLIDAY_STATE_GET_REQUEST';
export const HOLIDAY_STATE_GET_SUCCESS = ' HOLIDAY_STATE_GET_SUCCESS';
export const HOLIDAY_STATE_GET_FAILURE = ' HOLIDAY_STATE_GET_FAILURE';

export const LABOUR_WELFARE_STATE_GET_REQUEST = ' LABOUR_WELFARE_STATE_GET_REQUEST';
export const LABOUR_WELFARE_STATE_GET_SUCCESS = ' LABOUR_WELFARE_STATE_GET_SUCCESS';
export const LABOUR_WELFARE_STATE_GET_FAILURE = ' LABOUR_WELFARE_STATE_GET_FAILURE';


export const MINWAGE_LIBRARY_GET_REQUEST = 'MINWAGE_LIBRARY_GET_REQUEST';
export const MINWAGE_LIBRARY_GET_SUCCESS = 'MINWAGE_LIBRARY_GET_SUCCESS';
export const MINWAGE_LIBRARY_GET_FAILURE = 'MINWAGE_LIBRARY_GET_FAILURE';

export const MINWAGE_LIBRARY_GET_BY_ID_REQUEST = 'MINWAGE_LIBRARY_GET_BY_ID_REQUEST';
export const MINWAGE_LIBRARY_GET_BY_ID_SUCCESS = 'MINWAGE_LIBRARY_GET_BY_ID_SUCCESS';
export const MINWAGE_LIBRARY_GET_BY_ID_FAILURE = 'MINWAGE_LIBRARY_GET_BY_ID_FAILURE';


export const MINWAGE_PERIOD_LIBRARY_GET_REQUEST = 'MINWAGE_PERIOD_LIBRARY_GET_REQUEST';
export const MINWAGE_PERIOD_LIBRARY_GET_SUCCESS = 'MINWAGE_PERIOD_LIBRARY_GET_SUCCESS';
export const MINWAGE_PERIOD_LIBRARY_GET_FAILURE = 'MINWAGE_PERIOD_LIBRARY_GET_FAILURE';


export const WH_LR_STATE_GET_REQUEST = ' WH_LR_STATE_GET_REQUEST';
export const WH_LR_STATE_GET_SUCCESS = ' WH_LR_STATE_GET_SUCCESS';
export const WH_LR_STATE_GET_FAILURE = ' WH_LR_STATE_GET_FAILURE';


export const PT_STATE_GET_REQUEST = ' PT_STATE_GET_REQUEST';
export const PT_STATE_GET_SUCCESS = ' PT_STATE_GET_SUCCESS';
export const PT_STATE_GET_FAILURE = ' PT_STATE_GET_FAILURE';

export const REMITTANCE_CREATE_REQUEST = 'REMITTANCE_CREATE_REQUEST';
export const REMITTANCE_CREATE_SUCCESS = 'REMITTANCE_CREATE_SUCCESS';
export const REMITTANCE_CREATE_FAILURE = 'REMITTANCE_CREATE_FAILURE';

export const REMITTANCE_GET_REQUEST = 'REMITTANCE_GET_REQUEST';
export const REMITTANCE_GET_SUCCESS = 'REMITTANCE_GET_SUCCESS';
export const REMITTANCE_GET_FAILURE = 'REMITTANCE_GET_FAILURE';

export const REMITTANCE_EDIT_REQUEST = 'REMITTANCE_EDIT_REQUEST';
export const REMITTANCE_EDIT_SUCCESS = 'REMITTANCE_EDIT_SUCCESS';
export const REMITTANCE_EDIT_FAILURE = 'REMITTANCE_EDIT_FAILURE';

export const REMITTANCE_DELETE_REQUEST = 'REMITTANCE_DELETE_REQUEST';
export const REMITTANCE_DELETE_SUCCESS = 'REMITTANCE_DELETE_SUCCESS';
export const REMITTANCE_DELETE_FAILURE = 'REMITTANCE_DELETE_FAILURE';

export const REMITTANCE_GET_BY_ID_REQUEST = 'REMITTANCE_GET_BY_ID_REQUEST';
export const REMITTANCE_GET_BY_ID_SUCCESS = 'REMITTANCE_GET_BY_ID_SUCCESS';
export const REMITTANCE_GET_BY_ID_FAILURE = 'REMITTANCE_GET_BY_ID_FAILURE';


export const REGISTER_COMP_CREATE_REQUEST = 'REGISTER_COMP_CREATE_REQUEST';
export const REGISTER_COMP_CREATE_SUCCESS = 'REGISTER_COMP_CREATE_SUCCESS';
export const REGISTER_COMP_CREATE_FAILURE = 'REGISTER_COMP_CREATE_FAILURE';

export const REGISTER_COMP_GET_REQUEST = 'REGISTER_COMP_GET_REQUEST';
export const REGISTER_COMP_GET_SUCCESS = 'REGISTER_COMP_GET_SUCCESS';
export const REGISTER_COMP_GET_FAILURE = 'REGISTER_COMP_GET_FAILURE';

export const REGISTER_COMP_EDIT_REQUEST = 'REGISTER_COMP_EDIT_REQUEST';
export const REGISTER_COMP_EDIT_SUCCESS = 'REGISTER_COMP_EDIT_SUCCESS';
export const REGISTER_COMP_EDIT_FAILURE = 'REGISTER_COMP_EDIT_FAILURE';

export const REGISTER_COMP_DELETE_REQUEST = 'REGISTER_COMP_DELETE_REQUEST';
export const REGISTER_COMP_DELETE_SUCCESS = 'REGISTER_COMP_DELETE_SUCCESS';
export const REGISTER_COMP_DELETE_FAILURE = 'REGISTER_COMP_DELETE_FAILURE';

export const REGISTER_COMP_GET_BY_ID_REQUEST = 'REGISTER_COMP_GET_BY_ID_REQUEST';
export const REGISTER_COMP_GET_BY_ID_SUCCESS = 'REGISTER_COMP_GET_BY_ID_SUCCESS';
export const REGISTER_COMP_GET_BY_ID_FAILURE = 'REGISTER_COMP_GET_BY_ID_FAILURE';

export const RETURNS_CREATE_REQUEST = 'RETURNS_CREATE_REQUEST';
export const RETURNS_CREATE_SUCCESS = 'RETURNS_CREATE_SUCCESS';
export const RETURNS_CREATE_FAILURE = 'RETURNS_CREATE_FAILURE';

export const RETURNS_GET_REQUEST = 'RETURNS_GET_REQUEST';
export const RETURNS_GET_SUCCESS = 'RETURNS_GET_SUCCESS';
export const RETURNS_GET_FAILURE = 'RETURNS_GET_FAILURE';

export const RETURNS_EDIT_REQUEST = 'RETURNS_EDIT_REQUEST';
export const RETURNS_EDIT_SUCCESS = 'RETURNS_EDIT_SUCCESS';
export const RETURNS_EDIT_FAILURE = 'RETURNS_EDIT_FAILURE';

export const RETURNS_DELETE_REQUEST = 'RETURNS_DELETE_REQUEST';
export const RETURNS_DELETE_SUCCESS = 'RETURNS_DELETE_SUCCESS';
export const RETURNS_DELETE_FAILURE = 'RETURNS_DELETE_FAILURE';

export const RETURNS_GET_BY_ID_REQUEST = 'RETURNS_GET_BY_ID_REQUEST';
export const RETURNS_GET_BY_ID_SUCCESS = 'RETURNS_GET_BY_ID_SUCCESS';
export const RETURNS_GET_BY_ID_FAILURE = 'RETURNS_GET_BY_ID_FAILURE';

export const CATEGORY_COMPANY_REQUEST_GET = 'CATEGORY_COMPANY_REQUEST_GET';
export const CATEGORY_COMPANY_SUCCESS_GET = 'CATEGORY_COMPANY_SUCCESS_GET';
export const CATEGORY_COMPANY_GET_FAIL = 'CATEGORY_COMPANY_GET_FAIL';

export const CHECKLIST_BY_CATEO_REQUEST = 'CHECKLIST_BY_CATEO_REQUEST';
export const CHECKLIST_BY_CATEO_SUCCESS = 'CHECKLIST_BY_CATEO_SUCCESS';
export const CHECKLIST_BY_CATEO_FAILURE = 'CHECKLIST_BY_CATEO_FAILURE';

export const BRANCHES_DELETE_REQUEST = 'BRANCHES_DELETE_REQUEST';
export const BRANCHES_DELETE_SUCCESS = 'BRANCHES_DELETE_SUCCESS';
export const BRANCHES_DELETE_FAILURE = 'BRANCHES_DELETE_FAILURE';

export const BRANCHREQUEST_REQUEST = 'BRANCHREQUEST_REQUEST';
export const BRANCHREQUEST_SUCCESS = 'BRANCHREQUEST_SUCCESS';
export const BRANCHREQUEST_FAILURE = 'BRANCHREQUEST_FAILURE';

export const BRANCHREQUEST_ID_REQUEST = 'BRANCHREQUEST_ID_REQUEST';
export const BRANCHREQUEST_ID_SUCCESS = 'BRANCHREQUEST_ID_SUCCESS';
export const BRANCHREQUEST_ID_FAILURE = 'BRANCHREQUEST_ID_FAILURE';

export const BRANCH_CHECK_REQUEST = 'BRANCH_CHECK_REQUEST';
export const BRANCH_CHECK_SUCCESS = 'BRANCH_CHECK_SUCCESS';
export const BRANCH_CHECK_FAILURE = 'BRANCH_CHECK_FAILURE';

export const EXECUTIVECOMPANY_REQUEST_GET = 'EXECUTIVECOMPANY_REQUEST_GET';
export const EXECUTIVECOMPANY_SUCCESS_GET = 'EXECUTIVECOMPANY_SUCCESS_GET';
export const EXECUTIVECOMPANY_GET_FAIL = 'EXECUTIVECOMPANY_GET_FAIL';

export const BRANCHREQUEST_DELETE_REQUEST = 'BRANCHREQUEST_DELETE_REQUEST';
export const BRANCHREQUEST_DELETE_SUCCESS = 'BRANCHREQUEST_DELETE_SUCCESS';
export const BRANCHREQUEST_DELETE_FAILURE = 'BRANCHREQUEST_DELETE_FAILURE';

export const TEMPLATE_REGI_GET_REQUEST = 'TEMPLATE_REGI_GET_REQUEST';
export const TEMPLATE_REGI_GET_SUCCESS = 'TEMPLATE_REGI_GET_SUCCESS';
export const TEMPLATE_REGI_GET_FAILURE = 'TEMPLATE_REGI_GET_FAILURE';

export const TEMPLATE_REGI_UP_GET_REQUEST = 'TEMPLATE_REGI_UP_GET_REQUEST';
export const TEMPLATE_REGI_UP_GET_SUCCESS = 'TEMPLATE_REGI_UP_GET_SUCCESS';
export const TEMPLATE_REGI_UP_GET_FAILURE = 'TEMPLATE_REGI_UP_GET_FAILURE';

export const TEMPLATE_FORM_F_GET_REQUEST = 'TEMPLATE_FORM_F_GET_REQUEST';
export const TEMPLATE_FORM_F_GET_SUCCESS = 'TEMPLATE_FORM_F_GET_SUCCESS';
export const TEMPLATE_FORM_F_GET_FAILURE = 'TEMPLATE_FORM_F_GET_FAILURE';

export const TEMPLATE_FORM_F_PDF_GET_REQUEST = 'TEMPLATE_FORM_F_PDF_GET_REQUEST';
export const TEMPLATE_FORM_F_PDF_GET_SUCCESS = 'TEMPLATE_FORM_F_PDF_GET_SUCCESS';
export const TEMPLATE_FORM_F_PDF_GET_FAILURE = 'TEMPLATE_FORM_F_PDF_GET_FAILURE';

export const TEMPLATE_REGI_PDF_GET_REQUEST = 'TEMPLATE_REGI_PDF_GET_REQUEST';
export const TEMPLATE_REGI_PDF_GET_SUCCESS = 'TEMPLATE_REGI_PDF_GET_SUCCESS';
export const TEMPLATE_REGI_PDF_GET_FAILURE = 'TEMPLATE_REGI_PDF_GET_FAILURE';

export const TEMPLATE_FORM_D_GET_REQUEST = 'TEMPLATE_FORM_D_GET_REQUEST';
export const TEMPLATE_FORM_D_GET_SUCCESS = 'TEMPLATE_FORM_D_GET_SUCCESS';
export const TEMPLATE_FORM_D_GET_FAILURE = 'TEMPLATE_FORM_D_GET_FAILURE';

export const TEMPLATE_FORM_D_PDF_GET_REQUEST = 'TEMPLATE_FORM_D_PDF_GET_REQUEST';
export const TEMPLATE_FORM_D_PDF_GET_SUCCESS = 'TEMPLATE_FORM_D_PDF_GET_SUCCESS';
export const TEMPLATE_FORM_D_PDF_GET_FAILURE = 'TEMPLATE_FORM_D_PDF_GET_FAILURE';

export const TEMPLATE_FORM_C_GET_REQUEST = 'TEMPLATE_FORM_C_GET_REQUEST';
export const TEMPLATE_FORM_C_GET_SUCCESS = 'TEMPLATE_FORM_C_GET_SUCCESS';
export const TEMPLATE_FORM_C_GET_FAILURE = 'TEMPLATE_FORM_C_GET_FAILURE';

export const TEMPLATE_FORM_C_PDF_GET_REQUEST = 'TEMPLATE_FORM_C_PDF_GET_REQUEST';
export const TEMPLATE_FORM_C_PDF_GET_SUCCESS = 'TEMPLATE_FORM_C_PDF_GET_SUCCESS';
export const TEMPLATE_FORM_C_PDF_GET_FAILURE = 'TEMPLATE_FORM_C_PDF_GET_FAILURE';

export const TEMPLATE_FORM_A_GET_REQUEST = 'TEMPLATE_FORM_A_GET_REQUEST';
export const TEMPLATE_FORM_A_GET_SUCCESS = 'TEMPLATE_FORM_A_GET_SUCCESS';
export const TEMPLATE_FORM_A_GET_FAILURE = 'TEMPLATE_FORM_A_GET_FAILURE';

export const TEMPLATE_FORM_A_PDF_GET_REQUEST = 'TEMPLATE_FORM_A_PDF_GET_REQUEST';
export const TEMPLATE_FORM_A_PDF_GET_SUCCESS = 'TEMPLATE_FORM_A_PDF_GET_SUCCESS';
export const TEMPLATE_FORM_A_PDF_GET_FAILURE = 'TEMPLATE_FORM_A_PDF_GET_FAILURE';

export const REGI_INTIGRATE_REQUEST = 'REGI_INTIGRATE_REQUEST';
export const REGI_INTIGRATE_SUCCESS = 'REGI_INTIGRATE_SUCCESS';
export const REGI_INTIGRATE_FAILURE = 'REGI_INTIGRATE_FAILURE';

export const REGI_INTIGRATE_CREATE_REQUEST = 'REGI_INTIGRATE_CREATE_REQUEST';
export const REGI_INTIGRATE_CREATE_SUCCESS = 'REGI_INTIGRATE_CREATE_SUCCESS';
export const REGI_INTIGRATE_CREATE_FAILURE = 'REGI_INTIGRATE_CREATE_FAILURE';

export const REGI_INTIGRATE_GET_ALL_REQUEST = 'REGI_INTIGRATE_GET_ALL_REQUEST';
export const REGI_INTIGRATE_GET_ALL_SUCCESS = 'REGI_INTIGRATE_GET_ALL_SUCCESS';
export const REGI_INTIGRATE_GET_ALL_FAILURE = 'REGI_INTIGRATE_GET_ALL_FAILURE';